### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'is_written'

### ISSUE THREAD

**Issue by maxhbr** [JPEWdev/shacl2code#2]
When trying to run `JSONLDSerializer.write` the following line

https://github.com/JPEWdev/shacl2code/blob/f7075b29d4856305b78ce5e0871fc059ce5495f6/src/shacl2code/lang/templates/python.j2#L681

causes the following type error
```
Traceback (most recent call last):
...
  File ".../spdx3_0.py", line 1433, in write
    data = self.serialize_data(doc, force_graph)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../spdx3_0.py", line 1412, in serialize_data
    doc.encode(h, force_graph)
  File ".../spdx3_0.py", line 681, in encode
    if state.is_written(self):
       ^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'is_written'
```

## Used generated bindings:
this was observed with the bindings from https://github.com/spdx/spdx-3-serialization-prototype-playground/blob/055096eee3541464a126501f2e34816ef2f445bf/jsonld/bindings/spdx3_0.py

**Comment by maxhbr** [comment]
I think I mitigated by changing:
```diff
@@ -1409,7 +1409,7 @@ class JSONLDSerializer(object):
 
     def serialize_data(self, doc, force_graph=False):
         h = JSONLDEncoder()
-        doc.encode(h, force_graph)
+        doc.encode(h, EncodeState())
         data = {}
         if len(CONTEXT_URLS) == 1:
             data["@context"] = CONTEXT_URLS[0]
@@ -1550,7 +1550,7 @@ class JSONLDInlineSerializer(object):
 
         h.write('"@graph":')
 
-        doc.encode(h, True)
+        doc.encode(h, EncodeState())
         h.write("}")
         return sha1.hexdigest()
 

```

**Comment by JPEWdev** [comment]
Max,

I think your problem here is due to a poorly named class in the code bindings: I re-worked the serialization and deserialization to use the new `SHACLDocument` class which makes it easier to control how things are serialized and deserialized. You need to pass on of those as the `doc` parameter. My guess is that you are actually passing an `SPDXDocument` instead

**Comment by JPEWdev** [comment]
FYI, the code bindings have a `main()` function that does a noop copy from one file to another if you need a better example of how that's done.

**Comment by maxhbr** [comment]
I am passing an SPDXDocument as doc. The issue seems to be that instead of something of type `EncodeState` a bool is passed to the function.

**Comment by maxhbr** [comment]
ah, sorry, a `SHACLDocument`, will try that and naming is confusing, yes

**Comment by JPEWdev** [comment]
> ah, sorry, a `SHACLDocument`, will try that and naming is confusing, yes

Ya, Let me see if I can come up with a better name

**Comment by maxhbr** [comment]
Maybe "SHACLRecipe" or so?

**Comment by JPEWdev** [comment]
`SHACLDocument` was renamed `SHACLObjectSet` in 328a979e391536ca8bd68ba81670c8008ae5c5aa
