### ISSUE TITLE
Schema missing simpleLicensingInfo_AnyLicenseInfo class

### ISSUE THREAD

**Issue by goneall** [JPEWdev/shacl2code#23]
When generated against the latest model, the schema generated is missing the `$ref/simplelicensing_AnyLicenseInfo` definition.  It is also missing from the `anyClass` list.

Was this intentional?

Note that the `$ref/simplelicensing_AnyLicenseInfo_derived` is present.

**Comment by goneall** [comment]
The current generated schema can be found at: https://github.com/spdx/spdx-spec/blob/gh-pages/v3.0.1-draft/model/schema.json.

I noticed that there were a lot of referenced to the `undefined AnyLicenseInfo`, so I suspect this may be an issue.

**Comment by JPEWdev** [comment]
Ah, ya. That's a bug in the JSON schema validation; it's not skipping abstract classes
